pages/docs/data-ops.mdx
pages/docs/data-ops/cli.mdx
pages/docs/data-ops/quickstart.mdx
pages/docs/project-management/get-access-domains.mdx

Added some cards, Icons, and changed links to direct users to quickstart as the primary action

Update dev reference 

---

pages/docs/sharing-data-externally/sharing-to-slack.mdx

Slack app team has feeeeeedbaaaaaack.

Slack app review feedback.

---

pages/docs/data-ops.mdx
pages/docs/data-ops/cli.mdx
pages/docs/data-ops/cli/_meta.json
pages/docs/data-ops/cli/credentials.mdx
pages/docs/data-ops/cli/deploy.mdx
pages/docs/data-ops/cli/preview.mdx
pages/docs/data-ops/cli/token.mdx
pages/docs/data-ops/code-review.mdx
pages/docs/data-ops/managing-resources-with-code.mdx
pages/docs/data-ops/quickstart.mdx

[GL-5713] CLI Quickstart guide improvements.

---

pages/docs/guides/setup-alerting.mdx

add a guide to setting up alerting

guide, alerts

---

pages/docs/metrics.mdx

Open to suggestions for how best to phrase this.

Add metric owner to metric docs

---

pages/docs/dashboards/metrics.mdx
pages/docs/data-ops/config-schema.mdx
pages/docs/data-ops/config-schema/_meta.json
pages/docs/data-ops/config-schema/metrics.mdx
pages/docs/metrics.mdx

Should not be merged until https://github.com/gleannyc/glean/pull/9482 has been deployed

Update docs for metrics 

---

pages/docs/data-modeling/attributes.mdx

Adding "alias" and "make attribute hidden" to attribute docs

---

pages/docs/visualizing-data/chart-types.mdx

This should be good to go now.

Revert "Update chart types"

---

pages/docs/project-management/_meta.json
pages/docs/project-management/resource-lineage.mdx
pages/docs/project-management/resource-metadata.mdx

[HB-7320] Resource metadata docs

---

pages/docs/database-connections/_meta.json
pages/docs/database-connections/role-based-credentials.mdx

Won't be merged until the feature is out. LMK what ya'll think

[GRO-194] Documenting role-based credentials

---

pages/docs/sharing-data-externally/partner-projects.mdx

add a page for dans loom

---

next.config.js

Updates to point at latest entry

Update changelog redirect

---

pages/docs/visualizing-data/_meta.json
pages/docs/visualizing-data/adhoc-modeling.mdx

First pass at these docs. Won't merge until we've launched the feature ofc.
Data ops docs updates will be in a PR in the main repo.

[HB-7580] Documentation for adhocs

---

pages/docs/visualizing-data/chart-types.mdx
pages/docs/visualizing-data/controls/pivot-table-controls.mdx
pages/docs/visualizing-data/controls/table-controls.mdx

These will need to be updated again once we actually deprecate pivots 🗑️ 
Adds some documentation for table `columns` and some callouts that we'll be removing support for pivots soon

[HB-7670] Docs for table pivots

---

pages/docs/database-connections/_meta.json
pages/docs/database-connections/databricks.mdx

⚠️Not to be merged until Databricks feature flag is turned on 🚧

[GRO-423] Databricks documentation

---

pages/docs/_meta.json
pages/docs/sql-runner.mdx

[GRO-480] Add docs for SQL runner.

---

pages/docs/project-management/resource-history.mdx

This is a first pass on the documentation for resource history. 
closes HB-8084

Resource history docs

---

pages/docs/data-ops/environment-variables.mdx

Added a short section on this because it confused me when I was trying to develop YML for a dashboard that had a $ in a text block.

Adding explanation for escaping dollar signs in YML

---

pages/docs/visualizing-data/controls/table-controls.mdx

[HB-8250] Add documentation for subtotals

---

pages/docs/project-management/auto-archive.mdx

Resolves https://linear.app/hashboard/issue/HB-8414/add-documentation-for-auto-trashing-feature
Adding auto archive documentation:

Auto archive documentation

---

pages/docs/dashboards.mdx
pages/docs/project-management/resource-history.mdx
pages/docs/sharing-data-externally/public-links.mdx
pages/docs/users-and-permissions/permissions-overview.mdx

And fix one broken link.
closes HB-8610

Remove mentions of private resources

---

pages/docs/project-management/auto-archive.mdx

Documentation for Auto-archive:

[HB-8414] Documentation for auto archive

---

pages/docs/data-ops/cli/datasource.mdx

A line that I forgot to delete & made its way into documentation... 🤦‍♀️

Deleting line that was mistakenly included in documentation

---

pages/docs/project-management/resource-lineage.mdx

☝️ 
Resolves [HB-9103](https://linear.app/hashboard/issue/HB-9103/documentation-updates)
Updating the docs for accessing the resource lineage

[HB-9103] Resource lineage documentation updates

---

pages/docs/data-modeling/attributes.mdx

☝️ 
Resolves [HB-9203](https://linear.app/hashboard/issue/HB-9203/documentation-updates)

[HB-9203] Numeric attributes formatting docs update

---

pages/docs/guides/percentile-metrics.mdx

Came as customer request since it was difficult to discover

[HB-9396] Add median keyword to percentile docs

---

pages/docs/metrics.mdx

In addition to adding specifics about the metric tree, I updated the existing docs to account for the new metric modal and the fact that there are two tabs on the metrics page now.
closes HB-9558

[HB-9558] Initial metric tree docs

---

pages/docs/data-ops/continuous-integration.mdx

This works better with the newer async-style builds.

Updating sample github action

---

pages/docs/data-ops/dbt-integration.mdx
pages/docs/guides/prod-staging-environments.mdx

Queuing up for whenever we do our next prod release

Updated DBT default docs

---

pages/docs/data-ops/yaml-editor.mdx

Fix two broken links in YAML editor docs

---

pages/docs/data-ops/cli/v3/dbt-integration.mdx

add docs for database defer

---

pages/docs/data-ops/cli/v3/_meta.json
pages/docs/data-ops/cli/v3/install.mdx

preview: https://documentation-hashboard-git-ale-pipinstallalpha-glean-docs.vercel.app/docs/data-ops/cli/v3/install

add installation instructions for prerelease

---

pages/docs/faq.mdx

add an FAQ on how to handle timezones in Hashboard

add timezone faq

---

pages/docs/data-ops/resource-identifiers.mdx

https://documentation-hashboard-git-anna-updatedbtrefdocs-glean-docs.vercel.app/docs/data-ops/resource-identifiers

Update reference docs

---

components/MutedBlock.tsx
pages/docs/event-analytics/_meta.json
pages/docs/event-analytics/conversion-rates.mdx
pages/docs/event-analytics/funnels.mdx
pages/docs/event-analytics/overview.mdx

This revamps some of the docs to flesh out the existing options a bit more, how they work, etc. This also adds docs for breakouts.

[HB-10239] Documentation updates for funnels

---

pages/docs/visualizing-data/calculations.mdx

Documentation for min/max operators for calculations

---

pages/docs/data-ops/cli/_meta.json
pages/docs/data-ops/cli/v3/dbt-integration.mdx
pages/docs/data-ops/cli/v3/init.mdx
pages/docs/data-ops/dbt-integration.mdx

https://documentation-hashboard-git-anna-dbtupdates-glean-docs.vercel.app/docs/data-ops/cli/v3/install

Documentation updates for v3 beta 

---

pages/docs/sharing-data-externally/email-reports.mdx

[HB-10407] Add chart data option to email report docs

---

pages/docs/sharing-data-externally/_meta.json
pages/docs/sharing-data-externally/sharing-to-sheets.mdx

This follows the format of the email/slack integration documentation.
Not ready to be merged until the sheets integration is shipped – some things are also possibly subject to change here (like the errors section)

[HB-10128] Sheets integration setup docs

---

pages/docs/sharing-data-externally/email-reports.mdx
pages/docs/sharing-data-externally/sharing-to-slack.mdx

Documentation for PDF file format in email reports

---

pages/docs/data-modeling/add-data-model.mdx

Was causing a 404 error if you clicked

Invalid link fix

---

pages/docs/users-and-permissions/managing-users-and-roles.mdx

This PR reworks the roles page a bit have it work for the new role edit page layout as well as give mention to the concept of draft permissions.
closes HB-10916

[HB-10916] Update roles docs to mention draft permissions

---

pages/docs/data-modeling/_meta.json
pages/docs/data-modeling/default-exploration.mdx

[HB-11030] Default exploration docs

---

pages/docs/users-and-permissions/seat-types.mdx

We are planning to add seat type labels to the app itself, so it would be nice to have a place to link to explaining what this concept is.

Docs page on seat type

---

pages/docs/database-connections/snowflake.mdx

To merge later when the feature is ready.

[HB-11128] Snowflake key-pair auth documentation

---

pages/docs/database-connections/snowflake.mdx

Clarify snowflake account field docs

---

pages/docs/data-ops/cli/v3/init.mdx

Enumerates hbproject file options in one place and corresponding env vars 
https://documentation-hashboard-git-anna-hbproject-glean-docs.vercel.app/docs/data-ops/cli/v3/init#the-hbproject-file

Update to include more explicit details about the .hbproject files

---

pages/docs/dashboards.mdx

👆 
Resolves [HB-11588](https://linear.app/hashboard/issue/HB-11588/documentation-updates)

[HB-11588] Dashboard tabs - documentation updates
